#!/bin/bash

DIR=$(dirname `readlink -f $0`)
. $DIR/testing.conf
. $DIR/scripts/function.sh

echo "Stopping test environment"

NETWORKS="vnet1 vnet2 vnet3"
KNLTARGET=/var/run/kvm-swan-kernel
HOSTFSTARGET=/var/run/kvm-swan-hostfs
TESTRESULTSTARGET=/var/run/kvm-swan-testresults
#HOSTSRC=/var/run/kvm-strongswan

[ `id -u` -eq 0 ] || die "You must be root to run $0"

check_commands virsh

for net in $NETWORKS
do
	log_action "Network $net"
	execute "virsh net-destroy $net"
done

for host in $STRONGSWANHOSTS
do
	log_action "Guest $host"

	if running_any $host; then
		execute "virsh shutdown $host"
	else
		echo_warn "...not running"
	fi
	rm -f $VIRTIMGSTORE/$host.$IMGEXT
done

log_action "Removing kernel $KERNEL"
execute "rm $KNLTARGET"

log_action "Removing link to hostfs"
execute "rm $HOSTFSTARGET"

#log_action "Removing link to hostfs-src"
#execute "rm $HOSTSRC"

log_action "Removing link to testresults"
execute "rm $TESTRESULTSTARGET"

# Remove /etc/hosts entries
sudo sed -i '/^# DNS resolver for libvirt VM.*$/d' /etc/hosts >/dev/null

current_host=$(hostname)
for host in $STRONGSWANHOSTS
do
# Exclude the current hostname from deletion
    if [ "$host" != "$current_host" ]; then
        # Remove ipv4_${host} entry
        sudo sed -i "/^.*${host}\$/d" /etc/hosts >/dev/null
    fi
done